version: '3.9'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - db

  db:
    image: postgres
    container_name: "db-postgree"
    environment:
      POSTGRES_PASSWORD: neoway2023
      POSTGRES_USER: neoway2023
      POSTGRES_DB: clients
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
    volumes:
      - "./data/postgress:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080